### ISSUE TITLE
the column names for Signature_SNVs_xxxx counts.csv.bz2

### ISSUE THREAD

**Issue by qinghong2019** [garudlab/Signature-SNVs#1]
Hi, 
After generating the signature snvs, the csv does not have the column name. How do I know what does each column represent?

**Comment by LeahBriscoe** [comment]
Hi Qing Hong,

Thanks for your question and trying out our tool! The columns correspond to the same columns in your sink_sources.csv described in the README. For sanity check, you can also confirm that the read counts for a site matches the original SNV data. 

Hope this helps.
