### ISSUE TITLE
midas2 output

### ISSUE THREAD

**Issue by qinghong2019** [garudlab/Signature-SNVs#2]
Hi, I am using midas2 for SNVs. Since midas 1 is old, midas2 have detailed tutorials.  After merging the snvs across the samples using midas2, the samples without snvs were not included in the snps_depth and snps_ref_freq files. Is this the same as that in midas 1 merging output?  Could I use the results directly to calculate Signature-SNVs?

**Comment by LeahBriscoe** [comment]
Thank you for these questions and trying out our software! The MIDAS1 output has the same structure as the MIDAS2 output, where samples that don't have sufficient reads for a given species will not be represented in the snps_depth and snps_ref_freq files.  I've updated the README documentation to include a section on how to run SignatureSNVs with the output files from MIDAS2 I provided some lines of code for how to convert the output files into the MIDAS1-style output.
